# .github/workflows/daily-news.yml

name: Daily AI News Summary

on:
  schedule:
    # 매일 아침 9시(UTC 0시)에 실행
    - cron: "0 0 * * *"
  workflow_dispatch: # 수동 실행도 가능하도록 설정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-dotenv google-generativeai

      - name: Run summarizer and send to Kakao
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
        run: |
          python summarizer.py "AI 최신 동향"
