# .github/workflows/daily-news.yml

name: Daily AI News Summary

on:
  schedule:
    # 1. 매일 오전 6시 30분(KST)에 실행 (UTC 기준 전날 21:30)
    - cron: "30 21 * * *"
    # 2. 매일 오후 6시(KST)에 실행 (UTC 기준 당일 09:00)
    - cron: "0 9 * * *"
  workflow_dispatch: # 수동 실행도 가능하도록 설정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-dotenv google-generativeai

      - name: Run summarizer and send to Kakao
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
        run: |
          python summarizer.py "AI 최신 동향"
